services:
  mysql:
    container_name: 'data-base'
    image: 'mysql:8.0'
    environment:
      - 'MYSQL_DATABASE=myclinic'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=appdb'
    ports:
      - '3306:3306'
    volumes:
          - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
    ports:
      - 8080:8080
  volumes:
    mysql-data: